liip_imagine:
    filter_sets:
        cmi_product:
            filters:
                thumbnail:
                    size: [8000, 200]
                    mode: outbound




    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"
