sylius_resource:
    resources:
        app.supplier:
            driver: doctrine/orm # You can use also different driver here
            classes:
                model: App\Entity\Taxonomy\Taxon
        app.favorite:
            driver: doctrine/orm
            classes:
                model: App\Entity\Favorite\Favorite